In [1]:
import navis

n = navis.example_neurons(n=1)
n

type              TreeNeuron
name            neuron_38885
n_nodes                 6365
n_connectors               0
n_branches               235
n_leafs                  243
cable_length     1.21335e+06
soma                  [3490]
dtype: object

In [2]:
n.nodes.head()

node_id label         x         y         z  radius  parent_id  type
0        1     0  489192.0  186290.0  138040.0     0.0         -1  root
1        2     0  489233.0  186198.0  138080.0     0.0          1  slab
2        3     0  489235.0  186174.0  138120.0     0.0          2  slab
3        4     0  489229.0  186200.0  138160.0     0.0          3  slab
4        5     0  489251.0  186141.0  138200.0     0.0          4  slab

In [19]:
nl = navis.example_neurons(n=3)
nl

<class 'navis.core.neuronlist.NeuronList'> of 3 neurons 
          type            name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron    neuron_38885     6365             0         235      243   
1  TreeNeuron  neuron_1785034     8187             0         305      322   
2  TreeNeuron    neuron_57418     3839             0         134      142   

   cable_length    soma  
0  1.213347e+06  [3490]  
1  1.447682e+06  [3604]  
2  9.499755e+05  [2546]

In [4]:
nl[0]

type              TreeNeuron
name            neuron_38885
n_nodes                 6365
n_connectors               0
n_branches               235
n_leafs                  243
cable_length     1.21335e+06
soma                  [3490]
dtype: object

In [4]:
nl.n_nodes

array([6365, 8187, 3839])

In [5]:
nl.cable_length

array([1213347.43506801, 1447681.63642537,  949975.4839264 ])

In [ ]:
n.reroot(n.soma, inplace=True)
navis.reroot_neuron(n, n.soma, inplace=True)

In [ ]:
n.plot3d(color='red')
navis.plot3d(n, color='red')

In [ ]:
n.prune_by_volume('LH_R', inplace=True)
navis.in_volume(n, 'LH_R', inplace=True)

In [8]:
n = navis.example_neurons(1)
lh = navis.example_volume('LH')
n_lh = n.prune_by_volume(lh, inplace=False)
print(f'{n.n_nodes} nodes before and {n_lh.n_nodes} nodes after pruning')

6365 nodes before and 1299 nodes after pruning


In [2]:
nl = navis.example_neurons(n=3)

nl[[0, 2]]

<class 'navis.core.neuronlist.NeuronList'> of 2 neurons 
          type          name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron  neuron_38885     6365             0         235      243   
1  TreeNeuron  neuron_57418     3839             0         134      142   

   cable_length    soma  
0  1.213347e+06  [3490]  
1  9.499755e+05  [2546]

In [ ]:
... or slices

In [3]:
nl[:2]

<class 'navis.core.neuronlist.NeuronList'> of 2 neurons 
          type            name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron    neuron_38885     6365             0         235      243   
1  TreeNeuron  neuron_1785034     8187             0         305      322   

   cable_length    soma  
0  1.213347e+06  [3490]  
1  1.447682e+06  [3604]

In [7]:
subset = nl[nl.n_nodes > 7000]
subset

<class 'navis.core.neuronlist.NeuronList'> of 1 neurons 
          type            name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron  neuron_1785034     8187             0         305      322   

   cable_length    soma  
0  1.447682e+06  [3604]

In [15]:
nl.soma

array([[3490],
       [3604],
       [2546]])

In [8]:
import numpy as np

np.any(nl.soma, axis=1)

array([ True,  True,  True])

In [9]:
subset = nl[np.any(nl.soma, axis=1)]
subset

<class 'navis.core.neuronlist.NeuronList'> of 3 neurons 
          type            name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron    neuron_38885     6365             0         235      243   
1  TreeNeuron  neuron_1785034     8187             0         305      322   
2  TreeNeuron    neuron_57418     3839             0         134      142   

   cable_length    soma  
0  1.213347e+06  [3490]  
1  1.447682e+06  [3604]  
2  9.499755e+05  [2546]

In [10]:
nl['neuron_38885']

<class 'navis.core.neuronlist.NeuronList'> of 1 neurons 
          type          name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron  neuron_38885     6365             0         235      243   

   cable_length    soma  
0  1.213347e+06  [3490]

In [11]:
nl[['neuron_38885', 'neuron_57418']]

<class 'navis.core.neuronlist.NeuronList'> of 2 neurons 
          type          name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron  neuron_38885     6365             0         235      243   
1  TreeNeuron  neuron_57418     3839             0         134      142   

   cable_length    soma  
0  1.213347e+06  [3490]  
1  9.499755e+05  [2546]

In [16]:
nl['.*85.*']

<class 'navis.core.neuronlist.NeuronList'> of 2 neurons 
          type            name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron    neuron_38885     6365             0         235      243   
1  TreeNeuron  neuron_1785034     8187             0         305      322   

   cable_length    soma  
0  1.213347e+06  [3490]  
1  1.447682e+06  [3604]

In [9]:
nl[[0, 0]]

<class 'navis.core.neuronlist.NeuronList'> of 1 neurons 
          type          name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron  neuron_38885     6365             0         235      243   

   cable_length    soma  
0  1.213347e+06  [3490]

In [10]:
nl[[0, 'neuron_38885']]

<class 'navis.core.neuronlist.NeuronList'> of 1 neurons 
          type          name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron  neuron_38885     6365             0         235      243   

   cable_length    soma  
0  1.213347e+06  [3490]

In [17]:
[1] + [3]

[1, 3]

In [14]:
nl[:2] + nl[2:]

<class 'navis.core.neuronlist.NeuronList'> of 3 neurons 
          type            name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron    neuron_38885     6365             0         235      243   
1  TreeNeuron  neuron_1785034     8187             0         305      322   
2  TreeNeuron    neuron_57418     3839             0         134      142   

   cable_length    soma  
0  1.213347e+06  [3490]  
1  1.447682e+06  [3604]  
2  9.499755e+05  [2546]

In [13]:
nl[0] + nl[1]

<class 'navis.core.neuronlist.NeuronList'> of 2 neurons 
          type            name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron    neuron_38885     6365             0         235      243   
1  TreeNeuron  neuron_1785034     8187             0         305      322   

   cable_length    soma  
0  1.213347e+06  [3490]  
1  1.447682e+06  [3604]

In [16]:
l = [1, 2, 3]
l.pop(2)
l

[1, 2]

In [20]:
nl - nl[2]

<class 'navis.core.neuronlist.NeuronList'> of 2 neurons 
          type            name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron    neuron_38885     6365             0         235      243   
1  TreeNeuron  neuron_1785034     8187             0         305      322   

   cable_length    soma  
0  1.213347e+06  [3490]  
1  1.447682e+06  [3604]

In [21]:
set([0, 1, 2]) &  set([2, 3, 4])

{2}

In [22]:
nl[[0, 1]] & nl[[1, 2]]

<class 'navis.core.neuronlist.NeuronList'> of 1 neurons 
          type            name  n_nodes  n_connectors  n_branches  n_leafs  \
0  TreeNeuron  neuron_1785034     8187             0         305      322   

   cable_length    soma  
0  1.447682e+06  [3604]

In [23]:
n = nl[0]
n.nodes.head()

node_id label         x         y         z  radius  parent_id  type
0        1     0  489192.0  186290.0  138040.0     0.0         -1  root
1        2     0  489233.0  186198.0  138080.0     0.0          1  slab
2        3     0  489235.0  186174.0  138120.0     0.0          2  slab
3        4     0  489229.0  186200.0  138160.0     0.0          3  slab
4        5     0  489251.0  186141.0  138200.0     0.0          4  slab

In [24]:
n2 = n / 1000
n2.nodes.head()

node_id label        x        y       z  radius  parent_id  type
0        1     0  489.192  186.290  138.04     0.0         -1  root
1        2     0  489.233  186.198  138.08     0.0          1  slab
2        3     0  489.235  186.174  138.12     0.0          2  slab
3        4     0  489.229  186.200  138.16     0.0          3  slab
4        5     0  489.251  186.141  138.20     0.0          4  slab

In [17]:
1 == 1

True

In [18]:
2 == 1

False

In [5]:
nl[0] == nl[0]

True

In [6]:
nl[0] == nl[1]

False

In [3]:
navis.TreeNeuron.EQ_ATTRIBUTES

['n_nodes',
 'n_connectors',
 'soma',
 'root',
 'n_branches',
 'n_leafs',
 'cable_length',
 'name']

In [7]:
nl == nl

True

In [4]:
nl == nl[:2]

False

In [5]:
nl == nl[[2, 1, 0]]

False

In [6]:
nl[0] == nl[0].copy()

True

In [7]:
nl[0] == nl[0].downsample(2, inplace=False)

False

In [8]:
nl[0] in nl

True

In [9]:
nl[0] in nl[1:]

False

In [6]:
n = navis.example_neurons(1)

print(f'Nodes in node table: {n.nodes.shape[0]}')
print(f'Nodes in graph: {len(n.graph.nodes)}')

Nodes in node table: 6365
Nodes in graph: 6365


In [7]:
n.prune_by_strahler(1, inplace=True)

print(f'Nodes in node table: {n.nodes.shape[0]}')
print(f'Nodes in graph: {len(n.graph.nodes)}')

Nodes in node table: 4461
Nodes in graph: 4461


In [39]:
n = navis.example_neurons(1)

print(f'Nodes in node table before: {n.nodes.shape[0]}')
print(f'Nodes in graph before: {len(n.graph.nodes)}')

# Truncate the node table by 55 nodes
n.nodes = n.nodes.iloc[:-55]

print(f'\nNodes in node table after: {n.nodes.shape[0]}')
print(f'Nodes in graph after: {len(n.graph.nodes)}')

Nodes in node table before: 6365
Nodes in graph before: 6365

Nodes in node table after: 6310
Nodes in graph after: 6365


In [37]:
# Clear temporary attributes of the neuron
n._clear_temp_attr()

print(f'Nodes in node table after clear: {n.nodes.shape[0]}')
print(f'Nodes in graph after clear: {len(n.graph.nodes)}')

Nodes in node table after clear: 6310
Nodes in graph after clear: 6310
